import {
  FileImage,
  FileText,
  ImageIcon,
  Zap,
  Volume2,
  FileCheck,
  Shield,
  Video,
  Scissors,
  QrCode,
  BarChart3,
  Maximize,
  Droplets,
  RefreshCw,
  Type,
  FileSpreadsheet,
  FileSignature,
} from "lucide-react"

// Icon mapping for client-side use
export const iconMap = {
  FileImage,
  FileText,
  ImageIcon,
  Zap,
  Volume2,
  FileCheck,
  Shield,
  Video,
  Scissors,
  QrCode,
  BarChart3,
  Maximize,
  Droplets,
  RefreshCw,
  Type,
}

export const toolsData = [
  // Image Tools
  {
    id: "image-compressor",
    title: "Image Compressor",
    description: "Reduce image file sizes while maintaining quality",
    icon: ImageIcon,
    iconName: "ImageIcon",
    acceptedTypes: "image/*",
    color: "text-purple-600 dark:text-purple-400",
    bgColor: "bg-purple-50 dark:bg-purple-950/20",
    category: "Image Tools",
  },
  {
    id: "image-resizer",
    title: "Image Resizer",
    description: "Resize images to specific dimensions",
    icon: Maximize,
    iconName: "Maximize",
    acceptedTypes: "image/*",
    color: "text-indigo-600 dark:text-indigo-400",
    bgColor: "bg-indigo-50 dark:bg-indigo-950/20",
    category: "Image Tools",
  },
  {
    id: "image-watermarker",
    title: "Image Watermarker",
    description: "Add watermarks to protect your images",
    icon: Droplets,
    iconName: "Droplets",
    acceptedTypes: "image/*",
    color: "text-teal-600 dark:text-teal-400",
    bgColor: "bg-teal-50 dark:bg-teal-950/20",
    category: "Image Tools",
  },
  {
    id: "image-cropper",
    title: "Image Cropper",
    description: "Crop images to desired dimensions",
    icon: Scissors,
    iconName: "Scissors",
    acceptedTypes: "image/*",
    color: "text-magenta-600 dark:text-magenta-400",
    bgColor: "bg-magenta-50 dark:bg-magenta-950/20",
    category: "Image Tools",
  },

  {
    id: "png-to-jpg",
    title: "PNG to JPG Converter",
    description: "Convert PNG images to JPG format",
    icon: RefreshCw,
    iconName: "RefreshCw",
    acceptedTypes: "image/png",
    color: "text-blue-600 dark:text-blue-400",
    bgColor: "bg-blue-50 dark:bg-blue-950/20",
    category: "Image Tools",
  },
  {
    id: "png-to-jpeg",
    title: "PNG to JPEG Converter",
    description: "Convert PNG images to JPEG format",
    icon: RefreshCw,
    iconName: "RefreshCw",
    acceptedTypes: "image/jpeg",
    color: "text-green-600 dark:text-green-400",
    bgColor: "bg-green-50 dark:bg-green-950/20",
    category: "Image Tools",
  },
  {
    id: "png-to-svg",
    title: "PNG to SVG Converter",
    description: "Convert PNG images to SVG format",
    icon: RefreshCw,
    iconName: "RefreshCw",
    acceptedTypes: "image/png",
    color: "text-teal-600 dark:text-teal-400",
    bgColor: "bg-teal-50 dark:bg-teal-950/20",
    category: "Image Tools",
  },
  {
    id: "png-to-webp",
    title: "PNG to WebP Converter",
    description: "Convert PNG images to WebP format",
    icon: RefreshCw,
    iconName: "RefreshCw",
    acceptedTypes: "image/png",
    color: "text-orange-600 dark:text-orange-400",
    bgColor: "bg-orange-50 dark:bg-orange-950/20",
    category: "Image Tools",
  },
  {
    id: "jpg-to-png",
    title: "JPG to PNG Converter",
    description: "Convert JPG images to PNG format",
    icon: RefreshCw,
    iconName: "RefreshCw",
    acceptedTypes: "image/jpeg",
    color: "text-green-600 dark:text-green-400",
    bgColor: "bg-green-50 dark:bg-green-950/20",
    category: "Image Tools",
  },
  {
    id: "jpg-to-jpeg",
    title: "JPG to JPEG Converter",
    description: "Convert JPG images to JPEG format",
    icon: RefreshCw,
    iconName: "RefreshCw",
    acceptedTypes: "image/jpg",
    color: "text-purple-600 dark:text-purple-400",
    bgColor: "bg-purple-50 dark:bg-purple-950/20",
    category: "Image Tools",
  },
  {
    id: "jpg-to-svg",
    title: "JPG to SVG Converter",
    description: "Convert JPG images to SVG format",
    icon: RefreshCw,
    iconName: "RefreshCw",
    acceptedTypes: "image/jpg",
    color: "text-yellow-600 dark:text-yellow-400",
    bgColor: "bg-yellow-50 dark:bg-yellow-950/20",
    category: "Image Tools",
  },
  {
    id: "jpg-to-webp",
    title: "JPG to WebP Converter",
    description: "Convert JPG images to WebP format",
    icon: RefreshCw,
    iconName: "RefreshCw",
    acceptedTypes: "image/jpg",
    color: "text-cyan-600 dark:text-cyan-400",
    bgColor: "bg-cyan-50 dark:bg-cyan-950/20",
    category: "Image Tools",
  },
  {
    id: "jpeg-to-png",
    title: "JPEG to PNG Converter",
    description: "Convert JPEG images to PNG format",
    icon: RefreshCw,
    iconName: "RefreshCw",
    acceptedTypes: "image/jpeg",
    color: "text-green-600 dark:text-green-400",
    bgColor: "bg-green-50 dark:bg-green-950/20",
    category: "Image Tools",
  },
  {
    id: "jpeg-to-jpg",
    title: "JPEG to JPG Converter",
    description: "Convert JPEG images to JPG format",
    icon: RefreshCw,
    iconName: "RefreshCw",
    acceptedTypes: "image/jpeg",
    color: "text-indigo-600 dark:text-indigo-400",
    bgColor: "bg-indigo-50 dark:bg-indigo-950/20",
    category: "Image Tools",
  },
  {
    id: "jpeg-to-svg",
    title: "JPEG to SVG Converter",
    description: "Convert JPEG images to SVG format",
    icon: RefreshCw,
    iconName: "RefreshCw",
    acceptedTypes: "image/jpeg",
    color: "text-pink-600 dark:text-pink-400",
    bgColor: "bg-pink-50 dark:bg-pink-950/20",
    category: "Image Tools",
  },
  {
    id: "jpeg-to-webp",
    title: "JPEG to WebP Converter",
    description: "Convert JPEG images to WebP format",
    icon: RefreshCw,
    iconName: "RefreshCw",
    acceptedTypes: "image/jpeg",
    color: "text-indigo-600 dark:text-indigo-400",
    bgColor: "bg-indigo-50 dark:bg-indigo-950/20",
    category: "Image Tools",
  },

  {
    id: "webp-to-png",
    title: "WebP to PNG Converter",
    description: "Convert WebP images to PNG format",
    icon: RefreshCw,
    iconName: "RefreshCw",
    acceptedTypes: "image/webp",
    color: "text-red-600 dark:text-red-400",
    bgColor: "bg-red-50 dark:bg-red-950/20",
    category: "Image Tools",
  },
  {
    id: "webp-to-jpg",
    title: "WebP to JPG Converter",
    description: "Convert WebP images to JPG format",
    icon: RefreshCw,
    iconName: "RefreshCw",
    acceptedTypes: "image/webp",
    color: "text-lime-600 dark:text-lime-400",
    bgColor: "bg-lime-50 dark:bg-lime-950/20",
    category: "Image Tools",
  },
  {
    id: "webp-to-jpeg",
    title: "WebP to JPEG Converter",
    description: "Convert WebP images to JPEG format",
    icon: RefreshCw,
    iconName: "RefreshCw",
    acceptedTypes: "image/webp",
    color: "text-emerald-600 dark:text-emerald-400",
    bgColor: "bg-emerald-50 dark:bg-emerald-950/20",
    category: "Image Tools",
  },

  // PDF Tools
  {
    id: "image-to-pdf",
    title: "Image to PDF",
    description: "Convert images (JPG, PNG, WEBP) to PDF format",
    icon: FileImage,
    iconName: "FileImage",
    acceptedTypes: "image/*",
    color: "text-blue-600 dark:text-blue-400",
    bgColor: "bg-blue-50 dark:bg-blue-950/20",
    category: "PDF Tools",
  },
  {
    id: "doc-to-pdf",
    title: "ALL Document to PDF",
    description: "Convert Excel,Word & TXT files to PDF",
    icon: FileText,
    iconName: "FileText",
    acceptedTypes: ".xlsx,.xls,.csv,.docx,.txt,.html",
    color: "text-pink-600 dark:text-pink-400",
    bgColor: "bg-pink-50 dark:bg-pink-950/20",
    category: "PDF Tools",
  },
  {
    id: "excel-to-pdf",
    title: "Excel to PDF",
    description: "Convert Excel files to PDF",
    icon: FileText,
    iconName: "FileText",
    acceptedTypes: ".xlsx,.xls,.csv",
    color: "text-green-600 dark:text-green-400",
    bgColor: "bg-green-50 dark:bg-green-950/20",
    category: "PDF Tools",
  },
  {
    id: "word-to-pdf",
    title: "Word to PDF",
    description: "Convert Word files to PDF",
    icon: FileText,
    iconName: "FileText",
    acceptedTypes: ".docx",
    color: "text-yellow-600 dark:text-yellow-400",
    bgColor: "bg-yellow-200 dark:bg-yellow-400",
    category: "PDF Tools",
  },
  {
    id: "txt-to-pdf",
    title: "TXT to PDF",
    description: "Convert TXT files to PDF",
    icon: FileText,
    iconName: "FileText",
    acceptedTypes: ".txt",
    color: "text-orange-600 dark:text-orange-400",
    bgColor: "bg-orange-50 dark:bg-orange-950/20",
    category: "PDF Tools",
  },
  {
    id: "html-to-pdf",
    title: "HTML to PDF",
    description: "Convert HTML files to PDF documents",
    icon: FileText,
    iconName: "FileCode",
    acceptedTypes: ".html",
    color: "text-orange-600 dark:text-orange-400",
    bgColor: "bg-orange-50 dark:bg-orange-950/20",
    category: "PDF Tools",
  },


  {
    id: "pdf-to-txt",
    title: "PDF to TXT",
    description: "Extract all text from a PDF file",
    icon: FileText,
    iconName: "FileText",
    acceptedTypes: ".pdf",
    color: "text-blue-600 dark:text-blue-400",
    bgColor: "bg-blue-100", // Adjusted for better contrast
    category: "PDF Converters",
  },
  {
    id: "pdf-to-word",
    title: "PDF to Word",
    description: "Convert PDFs to editable Word (DOCX) files",
    icon: FileSignature,
    iconName: "FileSignature",
    acceptedTypes: ".pdf",
    color: "text-sky-600 dark:text-sky-400",
    bgColor: "bg-sky-100", // Adjusted for better contrast
    category: "PDF Converters",
  },
  {
    id: "pdf-to-excel",
    title: "PDF to Excel",
    description: "Extract data from PDF files into spreadsheets",
    icon: FileSpreadsheet,
    iconName: "FileSpreadsheet",
    acceptedTypes: ".pdf",
    color: "text-emerald-600 dark:text-emerald-400",
    bgColor: "bg-emerald-100", // Adjusted for better contrast
    category: "PDF Converters",
  },
  // Note: PDF to PDF/A is highly complex and typically requires a server-side
  // engine for proper validation, so it is excluded from this client-side implementation.

  // Text Tools
  {
    id: "text-to-speech",
    title: "Text to Speech",
    description: "Convert text to natural-sounding speech",
    icon: Volume2,
    iconName: "Volume2",
    acceptedTypes: undefined,
    color: "text-pink-600 dark:text-pink-400",
    bgColor: "bg-pink-50 dark:bg-pink-950/20",
    category: "Text Tools",
  },
  // {
  //   id: "text-summarizer",
  //   title: "Text Summarizer",
  //   description: "Summarize long texts into key points",
  //   icon: FileCheck,
  //   iconName: "FileCheck",
  //   acceptedTypes: undefined,
  //   color: "text-violet-600 dark:text-violet-400",
  //   bgColor: "bg-violet-50 dark:bg-violet-950/20",
  //   category: "Text Tools",
  // },
  {
    id: "grammar-checker",
    title: "Grammar Checker",
    description: "Check and correct grammar mistakes",
    icon: Type,
    iconName: "Type",
    acceptedTypes: undefined,
    color: "text-emerald-600 dark:text-emerald-400",
    bgColor: "bg-emerald-50 dark:bg-emerald-950/20",
    category: "Text Tools",
  },
  // {
  //   id: "text-encryptor",
  //   title: "Text Encryptor",
  //   description: "Encrypt and decrypt text securely",
  //   icon: Shield,
  //   iconName: "Shield",
  //   acceptedTypes: undefined,
  //   color: "text-red-600 dark:text-red-400",
  //   bgColor: "bg-red-50 dark:bg-red-950/20",
  //   category: "Text Tools",
  // },
  // {
  //   id: "ai-humanizer",
  //   title: "AI Text Humanizer",
  //   description: "Transform AI-generated text into natural language",
  //   icon: Zap,
  //   iconName: "Zap",
  //   acceptedTypes: undefined,
  //   color: "text-orange-600 dark:text-orange-400",
  //   bgColor: "bg-orange-50 dark:bg-orange-950/20",
  //   category: "Text Tools",
  // },

  // Video Tools
  // {
  //   id: "video-resizer",
  //   title: "Video Resizer",
  //   description: "Resize videos to different dimensions",
  //   icon: Video,
  //   iconName: "Video",
  //   acceptedTypes: "video/*",
  //   color: "text-rose-600 dark:text-rose-400",
  //   bgColor: "bg-rose-50 dark:bg-rose-950/20",
  //   category: "Video Tools",
  // },
  {
    id: "video-compressor",
    title: "Video Compressor",
    description: "Compress videos to reduce file size",
    icon: Video,
    iconName: "Video",
    acceptedTypes: "video/*",
    color: "text-amber-600 dark:text-amber-400",
    bgColor: "bg-amber-50 dark:bg-amber-950/20",
    category: "Video Tools",
  },
  {
    id: "video-trimmer",
    title: "Video Trimmer",
    description: "Trim and cut video segments",
    icon: Scissors,
    iconName: "Scissors",
    acceptedTypes: "video/*",
    color: "text-lime-600 dark:text-lime-400",
    bgColor: "bg-lime-50 dark:bg-lime-950/20",
    category: "Video Tools",
  },
  {
    id: "video-cropper",
    title: "Video Cropper",
    description: "Crop videos to desired dimensions",
    icon: Scissors,
    iconName: "Scissors",
    acceptedTypes: "video/*",
    color: "text-lime-600 dark:text-lime-400",
    bgColor: "bg-lime-50 dark:bg-lime-950/20",
    category: "Video Tools",
  },

  // Other Tools
  {
    id: "qr-generator",
    title: "QR Code Generator",
    description: "Generate QR codes for text, URLs, and more",
    icon: QrCode,
    iconName: "QrCode",
    acceptedTypes: undefined,
    color: "text-orange-600 dark:text-orange-400",
    bgColor: "bg-orange-50 dark:bg-orange-950/20",
    category: "Other Tools",
  },
  {
    id: "barcode-generator",
    title: "Barcode Generator",
    description: "Generate various types of barcodes",
    icon: BarChart3,
    iconName: "BarChart3",
    acceptedTypes: undefined,
    color: "text-stone-600 dark:text-stone-400",
    bgColor: "bg-stone-50 dark:bg-stone-950/20",
    category: "Other Tools",
  },
]
