import {
  FileImage,
  FileText,
  ImageIcon,
  Zap,
  Volume2,
  FileCheck,
  Shield,
  Video,
  Scissors,
  QrCode,
  BarChart3,
  Maximize,
  Droplets,
  RefreshCw,
  Type,
} from "lucide-react"

// Icon mapping for client-side use
export const iconMap = {
  FileImage,
  FileText,
  ImageIcon,
  Zap,
  Volume2,
  FileCheck,
  Shield,
  Video,
  Scissors,
  QrCode,
  BarChart3,
  Maximize,
  Droplets,
  RefreshCw,
  Type,
}

export const toolsData = [
  // Image Tools
  {
    id: "image-compressor",
    title: "Image Compressor",
    description: "Reduce image file sizes while maintaining quality",
    icon: ImageIcon,
    iconName: "ImageIcon",
    acceptedTypes: "image/*",
    color: "text-purple-600 dark:text-purple-400",
    bgColor: "bg-purple-50 dark:bg-purple-950/20",
    category: "Image Tools",
  },
  {
    id: "image-resizer",
    title: "Image Resizer",
    description: "Resize images to specific dimensions",
    icon: Maximize,
    iconName: "Maximize",
    acceptedTypes: "image/*",
    color: "text-indigo-600 dark:text-indigo-400",
    bgColor: "bg-indigo-50 dark:bg-indigo-950/20",
    category: "Image Tools",
  },
  {
    id: "image-converter",
    title: "Image Converter",
    description: "Convert images between different formats",
    icon: RefreshCw,
    iconName: "RefreshCw",
    acceptedTypes: "image/*",
    color: "text-cyan-600 dark:text-cyan-400",
    bgColor: "bg-cyan-50 dark:bg-cyan-950/20",
    category: "Image Tools",
  },
  {
    id: "image-watermarker",
    title: "Image Watermarker",
    description: "Add watermarks to protect your images",
    icon: Droplets,
    iconName: "Droplets",
    acceptedTypes: "image/*",
    color: "text-teal-600 dark:text-teal-400",
    bgColor: "bg-teal-50 dark:bg-teal-950/20",
    category: "Image Tools",
  },

  // PDF Tools
  {
    id: "image-to-pdf",
    title: "Image to PDF",
    description: "Convert images (JPG, PNG, WEBP) to PDF format",
    icon: FileImage,
    iconName: "FileImage",
    acceptedTypes: "image/*",
    color: "text-blue-600 dark:text-blue-400",
    bgColor: "bg-blue-50 dark:bg-blue-950/20",
    category: "PDF Tools",
  },
  {
    id: "doc-to-pdf",
    title: "Document to PDF",
    description: "Convert Excel and Word files to PDF",
    icon: FileText,
    iconName: "FileText",
    acceptedTypes: ".xlsx,.xls,.docx,.doc",
    color: "text-green-600 dark:text-green-400",
    bgColor: "bg-green-50 dark:bg-green-950/20",
    category: "PDF Tools",
  },

  // Text Tools
  {
    id: "text-to-speech",
    title: "Text to Speech",
    description: "Convert text to natural-sounding speech",
    icon: Volume2,
    iconName: "Volume2",
    acceptedTypes: undefined,
    color: "text-pink-600 dark:text-pink-400",
    bgColor: "bg-pink-50 dark:bg-pink-950/20",
    category: "Text Tools",
  },
  {
    id: "text-summarizer",
    title: "Text Summarizer",
    description: "Summarize long texts into key points",
    icon: FileCheck,
    iconName: "FileCheck",
    acceptedTypes: undefined,
    color: "text-violet-600 dark:text-violet-400",
    bgColor: "bg-violet-50 dark:bg-violet-950/20",
    category: "Text Tools",
  },
  {
    id: "grammar-checker",
    title: "Grammar Checker",
    description: "Check and correct grammar mistakes",
    icon: Type,
    iconName: "Type",
    acceptedTypes: undefined,
    color: "text-emerald-600 dark:text-emerald-400",
    bgColor: "bg-emerald-50 dark:bg-emerald-950/20",
    category: "Text Tools",
  },
  {
    id: "text-encryptor",
    title: "Text Encryptor",
    description: "Encrypt and decrypt text securely",
    icon: Shield,
    iconName: "Shield",
    acceptedTypes: undefined,
    color: "text-red-600 dark:text-red-400",
    bgColor: "bg-red-50 dark:bg-red-950/20",
    category: "Text Tools",
  },
  {
    id: "ai-humanizer",
    title: "AI Text Humanizer",
    description: "Transform AI-generated text into natural language",
    icon: Zap,
    iconName: "Zap",
    acceptedTypes: undefined,
    color: "text-orange-600 dark:text-orange-400",
    bgColor: "bg-orange-50 dark:bg-orange-950/20",
    category: "Text Tools",
  },

  // Video Tools
  {
    id: "video-resizer",
    title: "Video Resizer",
    description: "Resize videos to different dimensions",
    icon: Video,
    iconName: "Video",
    acceptedTypes: "video/*",
    color: "text-rose-600 dark:text-rose-400",
    bgColor: "bg-rose-50 dark:bg-rose-950/20",
    category: "Video Tools",
  },
  {
    id: "video-compressor",
    title: "Video Compressor",
    description: "Compress videos to reduce file size",
    icon: Video,
    iconName: "Video",
    acceptedTypes: "video/*",
    color: "text-amber-600 dark:text-amber-400",
    bgColor: "bg-amber-50 dark:bg-amber-950/20",
    category: "Video Tools",
  },
  {
    id: "video-trimmer",
    title: "Video Trimmer",
    description: "Trim and cut video segments",
    icon: Scissors,
    iconName: "Scissors",
    acceptedTypes: "video/*",
    color: "text-lime-600 dark:text-lime-400",
    bgColor: "bg-lime-50 dark:bg-lime-950/20",
    category: "Video Tools",
  },

  // Other Tools
  {
    id: "qr-generator",
    title: "QR Code Generator",
    description: "Generate QR codes for text, URLs, and more",
    icon: QrCode,
    iconName: "QrCode",
    acceptedTypes: undefined,
    color: "text-slate-600 dark:text-slate-400",
    bgColor: "bg-slate-50 dark:bg-slate-950/20",
    category: "Other Tools",
  },
  {
    id: "barcode-generator",
    title: "Barcode Generator",
    description: "Generate various types of barcodes",
    icon: BarChart3,
    iconName: "BarChart3",
    acceptedTypes: undefined,
    color: "text-stone-600 dark:text-stone-400",
    bgColor: "bg-stone-50 dark:bg-stone-950/20",
    category: "Other Tools",
  },
]
