import {
  FileImage,
  FileText,
  ImageIcon,
  Zap,
  Volume2,
  FileCheck,
  Shield,
  Video,
  Scissors,
  QrCode,
  BarChart3,
  Maximize,
  Droplets,
  RefreshCw,
  Type,
  FileSpreadsheet,
  FileSignature,
} from "lucide-react"

// Icon mapping for client-side use
export const iconMap = {
  FileImage,
  FileText,
  ImageIcon,
  Zap,
  Volume2,
  FileCheck,
  Shield,
  Video,
  Scissors,
  QrCode,
  BarChart3,
  Maximize,
  Droplets,
  RefreshCw,
  Type,
}

export const toolsData = [
  // Image Tools
  {
    id: "image-compressor",
    title: "Image Compressor",
    description: "Reduce image file sizes while maintaining quality",
    icon: ImageIcon,
    iconName: "ImageIcon",
    acceptedTypes: "image/*",
    color: "text-purple-600 dark:text-purple-400",
    bgColor: "bg-purple-50 dark:bg-purple-950/20",
    category: "Image Tools",
    metaTitle: "Online Image Compressor for Free Use | Smart Tools",
    metaDescription: 'Compress image files online without losing quality. Fast, free, and secure tool to reduce the file size of JPG, PNG, or JPEG images instantly.'
  },
  {
    id: "image-resizer",
    title: "Image Resizer",
    description: "Resize images to specific dimensions",
    icon: Maximize,
    iconName: "Maximize",
    acceptedTypes: "image/*",
    color: "text-indigo-600 dark:text-indigo-400",
    bgColor: "bg-indigo-50 dark:bg-indigo-950/20",
    category: "Image Tools",
    metaTitle: "Resize and Optimise Images Online Free | Smart Tools",
    metaDescription: 'Resize images online instantly. Adjust width and height in pixels to fit your image according to your needs. Free, easy-to-use tool with no quality loss.'
  },
  {
    id: "image-watermarker",
    title: "Image Watermarker",
    description: "Add watermarks to protect your images",
    icon: Droplets,
    iconName: "Droplets",
    acceptedTypes: "image/*",
    color: "text-teal-600 dark:text-teal-400",
    bgColor: "bg-teal-50 dark:bg-teal-950/20",
    category: "Image Tools",
    metaTitle: "Add Watermark to Images Easily | Smart Tools",
    metaDescription: 'Easily add custom text or logo watermarks to your images online. Protect your photos with a fast, free, and user-friendly tool. No design skills needed.'
  },
  {
    id: "image-cropper",
    title: "Image Cropper",
    description: "Crop images to desired dimensions",
    icon: Scissors,
    iconName: "Scissors",
    acceptedTypes: "image/*",
    color: "text-magenta-600 dark:text-magenta-400",
    bgColor: "bg-magenta-50 dark:bg-magenta-950/20",
    category: "Image Tools",
    metaTitle: "Crop and Resize Images in Seconds | Smart Tools",
    metaDescription: "Crop your images online with ease. Resize, trim, and focus on the exact part you want. Free, fast, and compatible with all major formats."
  },

  {
    id: "png-to-jpg",
    title: "PNG to JPG Converter",
    description: "Convert PNG images to JPG format",
    icon: RefreshCw,
    iconName: "RefreshCw",
    acceptedTypes: "image/png",
    color: "text-blue-600 dark:text-blue-400",
    bgColor: "bg-blue-50 dark:bg-blue-950/20",
    category: "Image Tools",
    metaTitle: "Instant PNG to JPG Conversion Tool | Smart Tools",
    metaDescription: 'Convert PNG images to high-quality JPG format online. Fast, free, and secure, no watermark, no sign-up. Just upload, convert, and download.'
  },
  {
    id: "png-to-jpeg",
    title: "PNG to JPEG Converter",
    description: "Convert PNG images to JPEG format",
    icon: RefreshCw,
    iconName: "RefreshCw",
    acceptedTypes: "image/jpeg",
    color: "text-green-600 dark:text-green-400",
    bgColor: "bg-green-50 dark:bg-green-950/20",
    category: "Image Tools",
    metaTitle: "Free PNG to JPEG File Converter | Smart Tools",
    metaDescription: 'Convert PNG images to JPEG with ease and speed. Free, high-quality output with no watermarks or logins. Just upload and download in seconds.'
  },
  {
    id: "png-to-svg",
    title: "PNG to SVG Converter",
    description: "Convert PNG images to SVG format",
    icon: RefreshCw,
    iconName: "RefreshCw",
    acceptedTypes: "image/png",
    color: "text-teal-600 dark:text-teal-400",
    bgColor: "bg-teal-50 dark:bg-teal-950/20",
    category: "Image Tools",
    metaTitle: "PNG to SVG Vector Conversion Online | Smart Tools",
    metaDescription: 'Transform PNG images into scalable SVG files online. Preserve quality, ideal for web and design. Free, simple, and watermark-free.'
  },
  {
    id: "png-to-webp",
    title: "PNG to WebP Converter",
    description: "Convert PNG images to WebP format",
    icon: RefreshCw,
    iconName: "RefreshCw",
    acceptedTypes: "image/png",
    color: "text-orange-600 dark:text-orange-400",
    bgColor: "bg-orange-50 dark:bg-orange-950/20",
    category: "Image Tools",
    metaTitle: "Free PNG to WebP Image Converter Online | Smart Tools",
    metaDescription: "Convert PNG images to WEBP format quickly and for free. Save space without losing quality using our fast and secure online image converter."
  },
  {
    id: "jpg-to-png",
    title: "JPG to PNG Converter",
    description: "Convert JPG images to PNG format",
    icon: RefreshCw,
    iconName: "RefreshCw",
    acceptedTypes: "image/jpeg",
    color: "text-green-600 dark:text-green-400",
    bgColor: "bg-green-50 dark:bg-green-950/20",
    category: "Image Tools",
    metaTitle: "Quick JPG to PNG Conversion Tools Free | Smart Tools",
    metaDescription: 'Easily convert JPG files to high-quality PNG format. Free online tool with no watermarks, sign-ups, or delays. Instant results in just a few clicks.'
  },
  {
    id: "jpg-to-jpeg",
    title: "JPG to JPEG Converter",
    description: "Convert JPG images to JPEG format",
    icon: RefreshCw,
    iconName: "RefreshCw",
    acceptedTypes: "image/jpg",
    color: "text-purple-600 dark:text-purple-400",
    bgColor: "bg-purple-50 dark:bg-purple-950/20",
    category: "Image Tools",
    metaTitle: 'Convert JPG to JPEG Quickly | Smart Tools',
    metaDescription: 'Convert JPG images to JPEG format instantly. Free online tool with high-speed performance and best quality retention. No signup required.'
  },
  {
    id: "jpg-to-svg",
    title: "JPG to SVG Converter",
    description: "Convert JPG images to SVG format",
    icon: RefreshCw,
    iconName: "RefreshCw",
    acceptedTypes: "image/jpg",
    color: "text-yellow-600 dark:text-yellow-400",
    bgColor: "bg-yellow-50 dark:bg-yellow-950/20",
    category: "Image Tools",
    metaTitle: 'Convert JPG to SVG Format Online | Smart Tools',
    metaDescription: 'Turn your JPG images into scalable SVG files in seconds. Free, fast, and simple, perfect for web use and design without losing quality.'
  },
  {
    id: "jpg-to-webp",
    title: "JPG to WebP Converter",
    description: "Convert JPG images to WebP format",
    icon: RefreshCw,
    iconName: "RefreshCw",
    acceptedTypes: "image/jpg",
    color: "text-cyan-600 dark:text-cyan-400",
    bgColor: "bg-cyan-50 dark:bg-cyan-950/20",
    category: "Image Tools",
    metaTitle: 'Free JPG to WebP Converter Online | Smart Tools',
    metaDescription: 'Easily convert JPG images to WebP format online. Save space with smaller file sizes. No sign-up, no watermark, 100% free and lightning fast.'
  },
  {
    id: "jpeg-to-png",
    title: "JPEG to PNG Converter",
    description: "Convert JPEG images to PNG format",
    icon: RefreshCw,
    iconName: "RefreshCw",
    acceptedTypes: "image/jpeg",
    color: "text-green-600 dark:text-green-400",
    bgColor: "bg-green-50 dark:bg-green-950/20",
    category: "Image Tools",
    metaTitle: "Convert JPEG to PNG Online in Seconds | Smart Tools",
    metaDescription: 'Convert JPEG images to high-quality PNG format online. Quick, free, and secure, no watermarks, no sign-up, just smooth and accurate conversions.'
  },
  {
    id: "jpeg-to-jpg",
    title: "JPEG to JPG Converter",
    description: "Convert JPEG images to JPG format",
    icon: RefreshCw,
    iconName: "RefreshCw",
    acceptedTypes: "image/jpeg",
    color: "text-indigo-600 dark:text-indigo-400",
    bgColor: "bg-indigo-50 dark:bg-indigo-950/20",
    category: "Image Tools",
    metaTitle: "Convert JPEG to JPG Instantly | Smart Tools",
    metaDescription: "Quickly convert JPEG images to JPG format online. Fast, free, and reliable tool with original image quality maintained during conversion."
  },
  {
    id: "jpeg-to-svg",
    title: "JPEG to SVG Converter",
    description: "Convert JPEG images to SVG format",
    icon: RefreshCw,
    iconName: "RefreshCw",
    acceptedTypes: "image/jpeg",
    color: "text-pink-600 dark:text-pink-400",
    bgColor: "bg-pink-50 dark:bg-pink-950/20",
    category: "Image Tools",
    metaTitle: "Convert JPEG to SVG Format Online | Smart Tools",
    metaDescription: 'Online JPEG to SVG converter , turn your images into scalable vector graphics in seconds. 100% free, no watermark, and no registration needed.'
  },
  {
    id: "jpeg-to-webp",
    title: "JPEG to WebP Converter",
    description: "Convert JPEG images to WebP format",
    icon: RefreshCw,
    iconName: "RefreshCw",
    acceptedTypes: "image/jpeg",
    color: "text-indigo-600 dark:text-indigo-400",
    bgColor: "bg-indigo-50 dark:bg-indigo-950/20",
    category: "Image Tools",
    metaTitle: "Free Online JPEG to WebP Converter | Smart Tools",
    metaDescription: "Convert JPEG images to WebP instantly with this free online tool. Reduce file size, speed up websites, and maintain great image quality, no signup needed."
  },

  {
    id: "webp-to-png",
    title: "WebP to PNG Converter",
    description: "Convert WebP images to PNG format",
    icon: RefreshCw,
    iconName: "RefreshCw",
    acceptedTypes: "image/webp",
    color: "text-red-600 dark:text-red-400",
    bgColor: "bg-red-50 dark:bg-red-950/20",
    category: "Image Tools",
    metaTitle: "Free WebP to PNG Image Converter | Smart Tools",
    metaDescription: 'Convert WebP images to PNG format instantly. Free, fast, and reliable tool, no quality loss, no sign-up, just drag, drop, and download.'
  },
  {
    id: "webp-to-jpg",
    title: "WebP to JPG Converter",
    description: "Convert WebP images to JPG format",
    icon: RefreshCw,
    iconName: "RefreshCw",
    acceptedTypes: "image/webp",
    color: "text-lime-600 dark:text-lime-400",
    bgColor: "bg-lime-50 dark:bg-lime-950/20",
    category: "Image Tools",
    metaTitle: "Instant WebP to JPG Conversion Tool Online | Smart Tools",
    metaDescription: "Convert WEBP images to JPG format online with this free and easy tool. Ensure compatibility, preserve image quality, and download results instantly."
  },
  {
    id: "webp-to-jpeg",
    title: "WebP to JPEG Converter",
    description: "Convert WebP images to JPEG format",
    icon: RefreshCw,
    iconName: "RefreshCw",
    acceptedTypes: "image/webp",
    color: "text-emerald-600 dark:text-emerald-400",
    bgColor: "bg-emerald-50 dark:bg-emerald-950/20",
    category: "Image Tools",
    metaTitle: "WebP to JPG High-Quality Converter | Smart Tools",
    metaDescription: 'Easily convert WEBP images to JPEG format online. Quick, high-quality conversions without installing any software. 100% free and secure.'
  },

  // PDF Tools
  {
    id: "image-to-pdf",
    title: "Image to PDF",
    description: "Convert images (JPG, PNG, WEBP) to PDF format",
    icon: FileImage,
    iconName: "FileImage",
    acceptedTypes: "image/*",
    color: "text-blue-600 dark:text-blue-400",
    bgColor: "bg-blue-50 dark:bg-blue-950/20",
    category: "PDF Tools",
    metaTitle: "Convert Images to PDF Format Easily | Smart Tools",
    metaDescription: 'Convert images to PDF format easily. Supports JPG, PNG, and more. Free, fast, and secure, merge multiple images into a single PDF instantly.'
  },
  {
    id: "doc-to-pdf",
    title: "ALL Document to PDF",
    description: "Convert Excel,Word & TXT files to PDF",
    icon: FileText,
    iconName: "FileText",
    acceptedTypes: ".xlsx,.xls,.csv,.docx,.txt,.html",
    color: "text-pink-600 dark:text-pink-400",
    bgColor: "bg-pink-50 dark:bg-pink-950/20",
    category: "PDF Tools",
    metaTitle: "Convert Document Files to PDF Fast | Smart Tools",
    metaDescription: "Easily convert Document files to PDF online. Fast, reliable, and free tool to preserve your document layout and share files effortlessly."
  },
  {
    id: "excel-to-pdf",
    title: "Excel to PDF",
    description: "Convert Excel files to PDF",
    icon: FileText,
    iconName: "FileText",
    acceptedTypes: ".xlsx,.xls,.csv",
    color: "text-green-600 dark:text-green-400",
    bgColor: "bg-green-50 dark:bg-green-950/20",
    category: "PDF Tools",
    metaTitle: "Convert Excel Files to PDF Instantly | Smart Tools",
    metaDescription: "Easily convert Excel files to high-quality PDF documents online. Fast, secure, and free, no sign-up required. Try the Excel to PDF tool now!"
  },
  {
    id: "word-to-pdf",
    title: "Word to PDF",
    description: "Convert Word files to PDF",
    icon: FileText,
    iconName: "FileText",
    acceptedTypes: ".docx",
    color: "text-yellow-600 dark:text-yellow-400",
    bgColor: "bg-yellow-200 dark:bg-yellow-400",
    category: "PDF Tools",
    metaTitle: "Convert Word Documents to PDF Online | Smart Tools",
    metaDescription: 'Convert Word documents to PDF online with perfect formatting. Completely free, fast, and secure, no watermark, no registration required.'
  },
  {
    id: "txt-to-pdf",
    title: "TXT to PDF",
    description: "Convert TXT files to PDF",
    icon: FileText,
    iconName: "FileText",
    acceptedTypes: ".txt",
    color: "text-orange-600 dark:text-orange-400",
    bgColor: "bg-orange-50 dark:bg-orange-950/20",
    category: "PDF Tools",
    metaTitle: "Convert Text Files to PDF Format Online | Smart Tools",
    metaDescription: 'Convert plain text (TXT) files to PDF instantly. Easy, free, and secure tool with no watermarks or sign-up required. Just upload and download.'
  },
  {
    id: "html-to-pdf",
    title: "HTML to PDF",
    description: "Convert HTML files to PDF documents",
    icon: FileText,
    iconName: "FileCode",
    acceptedTypes: ".html",
    color: "text-orange-600 dark:text-orange-400",
    bgColor: "bg-orange-50 dark:bg-orange-950/20",
    category: "PDF Tools",
    metaTitle: "Convert HTML Pages to PDF Format | Smart Tools",
    metaDescription: 'Convert HTML files or web pages to high-quality PDF documents. Free, fast,instant and accurate, no sign-up or software installation required.'
  },

  // {
  //   id: "pdf-to-txt",
  //   title: "PDF to TXT",
  //   description: "Extract all text from a PDF file",
  //   icon: FileText,
  //   iconName: "FileText",
  //   acceptedTypes: ".pdf",
  //   color: "text-blue-600 dark:text-blue-400",
  //   bgColor: "bg-blue-100", // Adjusted for better contrast
  //   category: "PDF Tools",
  // metaTitle:'Extract Text from PDF Files Online | Smart Tools',
  // metaDescription:'Extract plain text from PDF files with our free online PDF to TXT converter. Fast, simple, and perfect for copying or editing text content.'
  // },
  // {
  //   id: "pdf-to-word",
  //   title: "PDF to Word",
  //   description: "Convert PDFs to editable Word (DOCX) files",
  //   icon: FileSignature,
  //   iconName: "FileSignature",
  //   acceptedTypes: ".pdf",
  //   color: "text-sky-600 dark:text-sky-400",
  //   bgColor: "bg-sky-100", // Adjusted for better contrast
  //   category: "PDF Tools",
  // metaTitle:"Convert PDF to Editable Word Files | Smart Tools",
  // metaDescription:"Convert PDF files to fully editable Word documents online. Fast, free, and reliable tool that accurately preserves layout, text, and formatting every time."
  // },
  // {
  //   id: "pdf-to-excel",
  //   title: "PDF to Excel",
  //   description: "Extract data from PDF files into spreadsheets",
  //   icon: FileSpreadsheet,
  //   iconName: "FileSpreadsheet",
  //   acceptedTypes: ".pdf",
  //   color: "text-emerald-600 dark:text-emerald-400",
  //   bgColor: "bg-emerald-100", // Adjusted for better contrast
  //   category: "PDF Tools",
  // metaDescription:"Convert PDF files to editable Excel spreadsheets effortlessly. Free and fast tool, extract tables with accurate formatting and no hassle."
  // },
  // Note: PDF to PDF/A is highly complex and typically requires a server-side
  // engine for proper validation, so it is excluded from this client-side implementation.

  // Text Tools
  {
    id: "text-to-speech",
    title: "Text to Speech",
    description: "Convert text to natural-sounding speech",
    icon: Volume2,
    iconName: "Volume2",
    acceptedTypes: undefined,
    color: "text-pink-600 dark:text-pink-400",
    bgColor: "bg-pink-50 dark:bg-pink-950/20",
    category: "Text Tools",
    metaTitle: "Convert Text to Natural Speech | Smart Tools",
    metaDescription: 'Convert text to life like speech in seconds. Choose from multiple voices and languages. Fast, free, and user-friendly online tool.'
  },
  // {
  //   id: "text-summarizer",
  //   title: "Text Summarizer",
  //   description: "Summarize long texts into key points",
  //   icon: FileCheck,
  //   iconName: "FileCheck",
  //   acceptedTypes: undefined,
  //   color: "text-violet-600 dark:text-violet-400",
  //   bgColor: "bg-violet-50 dark:bg-violet-950/20",
  //   category: "Text Tools",
  // },
  {
    id: "grammar-checker",
    title: "Grammar Checker",
    description: "Check and correct grammar mistakes",
    icon: Type,
    iconName: "Type",
    acceptedTypes: undefined,
    color: "text-emerald-600 dark:text-emerald-400",
    bgColor: "bg-emerald-50 dark:bg-emerald-950/20",
    category: "Text Tools",
    metaTitle: "Advanced Free Online Grammar Checker | Smart Tools",
    metaDescription: 'Check grammar, punctuation, and spelling instantly with our free grammar checker. Improve your writing online, no login, no cost, just accuracy.'
  },
  // {
  //   id: "text-encryptor",
  //   title: "Text Encryptor",
  //   description: "Encrypt and decrypt text securely",
  //   icon: Shield,
  //   iconName: "Shield",
  //   acceptedTypes: undefined,
  //   color: "text-red-600 dark:text-red-400",
  //   bgColor: "bg-red-50 dark:bg-red-950/20",
  //   category: "Text Tools",
  // },
  // {
  //   id: "ai-humanizer",
  //   title: "AI Text Humanizer",
  //   description: "Transform AI-generated text into natural language",
  //   icon: Zap,
  //   iconName: "Zap",
  //   acceptedTypes: undefined,
  //   color: "text-orange-600 dark:text-orange-400",
  //   bgColor: "bg-orange-50 dark:bg-orange-950/20",
  //   category: "Text Tools",
  // },

  // Video Tools
  // {
  //   id: "video-resizer",
  //   title: "Video Resizer",
  //   description: "Resize videos to different dimensions",
  //   icon: Video,
  //   iconName: "Video",
  //   acceptedTypes: "video/*",
  //   color: "text-rose-600 dark:text-rose-400",
  //   bgColor: "bg-rose-50 dark:bg-rose-950/20",
  //   category: "Video Tools",
  // },
  {
    id: "video-compressor",
    title: "Video Compressor",
    description: "Compress videos to reduce file size",
    icon: Video,
    iconName: "Video",
    acceptedTypes: "video/*",
    color: "text-amber-600 dark:text-amber-400",
    bgColor: "bg-amber-50 dark:bg-amber-950/20",
    category: "Video Tools",
    metaTitle: "Compress Videos Without Quality Loss | Smart Tools",
    metaDescription: 'Compress video files without losing quality. Reduce file size online in seconds, free, secure, and no watermark. All formats supported.'
  },
  {
    id: "video-trimmer",
    title: "Video Trimmer",
    description: "Trim and cut video segments",
    icon: Scissors,
    iconName: "Scissors",
    acceptedTypes: "video/*",
    color: "text-lime-600 dark:text-lime-400",
    bgColor: "bg-lime-50 dark:bg-lime-950/20",
    category: "Video Tools",
    metaTitle: "Trim Video Clips Easily and Free | Smart Tools",
    metaDescription: 'Trim your videos instantly online. Cut unwanted parts and keep only what you need with this fast, free, and easy-to-use video trimming tool.'
  },
  {
    id: "video-cropper",
    title: "Video Cropper",
    description: "Crop videos to desired dimensions",
    icon: Scissors,
    iconName: "Scissors",
    acceptedTypes: "video/*",
    color: "text-lime-600 dark:text-lime-400",
    bgColor: "bg-lime-50 dark:bg-lime-950/20",
    category: "Video Tools",
    metaTitle: "Crop Videos Online Easily & Free | Smart Tools",
    metaDescription: 'Crop videos online with precision using our free video cropper. Remove unwanted edges and frame your video perfectly without any software installation.'
  },

  // Other Tools
  {
    id: "qr-generator",
    title: "QR Code Generator",
    description: "Generate QR codes for text, URLs, and more",
    icon: QrCode,
    iconName: "QrCode",
    acceptedTypes: undefined,
    color: "text-orange-600 dark:text-orange-400",
    bgColor: "bg-orange-50 dark:bg-orange-950/20",
    category: "Other Tools",
    metaTitle: "Create Free Custom QR Codes Online | Smart Tools",
    metaDescription: 'Create custom QR codes for URLs, text, or contact info in seconds. 100% free, no login needed, download high-resolution QR codes instantly.'
  },
  {
    id: "barcode-generator",
    title: "Barcode Generator",
    description: "Generate various types of barcodes",
    icon: BarChart3,
    iconName: "BarChart3",
    acceptedTypes: undefined,
    color: "text-stone-600 dark:text-stone-400",
    bgColor: "bg-stone-50 dark:bg-stone-950/20",
    category: "Other Tools",
    metaTitle: "Generate Free Barcodes Easily for Online| Smart Tools",
    metaDescription: 'Create custom barcodes in seconds with our free online barcode generator. No registration, no watermark, just easy and fast barcode creation.'
  },
]
